version: '3'

services:
  terradnode0:
    container_name: terradnode0
    image: "terraproject/core"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=$${LOG:-terrad.log}
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  terradnode1:
    container_name: terradnode1
    image: "terraproject/core"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=$${LOG:-terrad.log}
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  terradnode2:
    container_name: terradnode2
    image: "terraproject/core"
    environment:
      - ID=2
      - LOG=$${LOG:-terrad.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  terradnode3:
    container_name: terradnode3
    image: "terraproject/core"
    environment:
      - ID=3
      - LOG=$${LOG:-terrad.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

