version: '3.8'

services:
  terradnode0:
    platform: linux/amd64
    container_name: terradnode0
    image: classic-terra/terrad-env
    ports:
      - "9090:9090"
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=$${LOG:-terrad.log}
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  terradnode1:
    platform: linux/amd64
    container_name: terradnode1
    image: classic-terra/terrad-env
    ports:
      - "9091:9090"
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=$${LOG:-terrad.log}
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  terradnode2:
    platform: linux/amd64
    container_name: terradnode2
    image: classic-terra/terrad-env
    environment:
      - ID=2
      - LOG=$${LOG:-terrad.log}
    ports:
      - "9092:9090"
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  terradnode3:
    platform: linux/amd64
    container_name: terradnode3
    image: classic-terra/terrad-env
    environment:
      - ID=3
      - LOG=$${LOG:-terrad.log}
    ports:
      - "9093:9090"
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  terradnode4:
    platform: linux/amd64
    container_name: terradnode4
    image: classic-terra/terrad-env
    environment:
      - ID=4
      - LOG=$${LOG:-terrad.log}
    ports:
      - "9094:9090"
      - "26665-26666:26656-26657"
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.6

  terradnode5:
    platform: linux/amd64
    container_name: terradnode5
    image: classic-terra/terrad-env
    environment:
      - ID=5
      - LOG=$${LOG:-terrad.log}
    ports:
      - "9095:9090"
      - "26667-26668:26656-26657"
    volumes:
      - ./build:/terrad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.7

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
